#!/usr/bin/env bash

# setup firewall in web-01 && web-02 && lb-01

sudo apt update -y;
sudo apt install ufw;
sudo ufw status;
sudo ufw default deny incoming;
sudo ufw default allow outgoing;
sudo ufw enable -y;
sudo ufw allow 22/tcp;
sudo ufw allow 443/tcp;
sudo ufw allow 80/tcp;
sudo ufw status;

