#!/usr/bin/env bash
# scirpt Name : 100-fix_in_7_lines_or_less
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i s/'80 default_server'/'8080 default_server'/g /etc/nginx/sites-available/default
sudo -u nginx service nginx start

